version: 2    
updates:
  - directory: /
    package-ecosystem: nuget
    ignore:
      - dependency-name: BepInEx.Core
      - dependency-name: HarmonyX
      - dependency-name: UnityEngine.Modules
      # Exclude AssetHelperLib because any changes to it may constitute breaking changes
      - dependency-name: AssetHelperLib
    schedule:
      interval: daily
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
  - directory: /
    package-ecosystem: gitsubmodule
    schedule:
      interval: daily
